defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  notes:
    output: true

title: Andrea Grillo's Blog
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal blog where I occasionaly writes about the technologies I
  love the most or that I am currently studying (like devops, p2p, and
  blockchains). My craft tools at the moment are C++, Go and Python.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: andregri
linkedin_username: andrea-grillo-3b439b1a9
