name: Publish new posts to medium
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run action
      uses: andregri/BlogOps@v1
      with:
        posts_dir: './_posts/'
        repo_name: "andregri.github.io"
        gh_access_token: ${{ secrets.GH_ACCESS_TOKEN }}
        medium_integration_token: ${{ secrets.MEDIUM_INTEGRATION_TOKEN }}